language: android

env:
  global:
  - ANDROID_API=27
  - ANDROID_BUILD_TOOLS=27.0.3

android:
  components:
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - ".+"
  
jdk:
- oraclejdk8

script: if [[ "$TRAVIS_BRANCH" == "master" ]]; then ./gradlew clean :app:assembleDebug; else ./gradlew clean test; fi

branches:
  except:
  - images
  - gh-pages
  - travis-build
  - i18n
  
notifications:
  email: false
  slack:
    rooms: jahirfiquitiva:StCMaxV85iad38DdSMBY43xW
    template:
    - 'Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}: ''%{commit_subject}''>)  by
      %{author} for %{repository_name}@%{branch}, %{result} in %{duration}. <%{build_url}|Check
      details>.'
      
sudo: false

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

before_script:
- chmod +x gradlew

before_install:
- yes | sdkmanager "platforms;android-27"

before_deploy:
  - git tag -f travis-build
  - git remote add gh
    https://${TRAVIS_REPO_SLUG%/*}:${GITHUB_API_KEY}@github.com/${TRAVIS_REPO_SLUG}.git
  - git push -f gh travis-build
  - git remote remove gh

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file_glob: true
  file: app/build/outputs/apk/debug/*.apk
  skip_cleanup: true
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  name: Frames APK Build
  body: Automated Frames APK build ($TRAVIS_COMMIT) made by Travis CI on $(date +'%F %T %Z').
  on:
    branch: master
    repo: jahirfiquitiva/Frames
    tags: true